// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWAvepnVQ9JfsKbGhURQraFDN8ctUj2Os',
    appId: '1:812616730462:web:0230bc2f52f589be3a31cf',
    messagingSenderId: '812616730462',
    projectId: 'productcatelogue-61478',
    authDomain: 'productcatelogue-61478.firebaseapp.com',
    storageBucket: 'productcatelogue-61478.appspot.com',
    measurementId: 'G-QJ9S7PE1N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-LsCzjDF2hQ43gN8pAGc-8ELEF2kRUhc',
    appId: '1:812616730462:android:808c122c1728fac43a31cf',
    messagingSenderId: '812616730462',
    projectId: 'productcatelogue-61478',
    storageBucket: 'productcatelogue-61478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-yNO8CJKtifF2F2IWRPGCZi2CdessqRQ',
    appId: '1:812616730462:ios:397114809aa0166f3a31cf',
    messagingSenderId: '812616730462',
    projectId: 'productcatelogue-61478',
    storageBucket: 'productcatelogue-61478.appspot.com',
    iosBundleId: 'com.example.productCatelogue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-yNO8CJKtifF2F2IWRPGCZi2CdessqRQ',
    appId: '1:812616730462:ios:397114809aa0166f3a31cf',
    messagingSenderId: '812616730462',
    projectId: 'productcatelogue-61478',
    storageBucket: 'productcatelogue-61478.appspot.com',
    iosBundleId: 'com.example.productCatelogue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWAvepnVQ9JfsKbGhURQraFDN8ctUj2Os',
    appId: '1:812616730462:web:691a3f82c40bb1f33a31cf',
    messagingSenderId: '812616730462',
    projectId: 'productcatelogue-61478',
    authDomain: 'productcatelogue-61478.firebaseapp.com',
    storageBucket: 'productcatelogue-61478.appspot.com',
    measurementId: 'G-HHBQV6PFWL',
  );
}
